set_property PACKAGE_PIN R2 [ get_ports rstn]
set_property IOSTANDARD LVCMOS33 [ get_ports rstn]
set_property PACKAGE_PIN W19 [ get_ports in[0]]
set_property IOSTANDARD LVCMOS33 [ get_ports in[0]]
set_property PACKAGE_PIN U17 [ get_ports in[1]]
set_property IOSTANDARD LVCMOS33 [ get_ports in[1]]
set_property PACKAGE_PIN T17 [ get_ports in[2]]
set_property IOSTANDARD LVCMOS33 [ get_ports in[2]]
set_property PACKAGE_PIN T18 [ get_ports in[3]]
set_property IOSTANDARD LVCMOS33 [ get_ports in[3]]
#switch
set_property PACKAGE_PIN V17 [get_ports swnum]    		
	set_property IOSTANDARD LVCMOS33 [get_ports swnum]
set_property PACKAGE_PIN V16 [get_ports swdigit]					
	set_property IOSTANDARD LVCMOS33 [get_ports swdigit]
set_property PACKAGE_PIN W15 [get_ports operations[10]]					
	set_property IOSTANDARD LVCMOS33 [get_ports operations[10]]
set_property PACKAGE_PIN V15 [get_ports operations[9]]					
	set_property IOSTANDARD LVCMOS33 [get_ports operations[9]]
set_property PACKAGE_PIN W14 [get_ports operations[8]]					
	set_property IOSTANDARD LVCMOS33 [get_ports operations[8]]
set_property PACKAGE_PIN W13 [get_ports operations[7]]					
	set_property IOSTANDARD LVCMOS33 [get_ports operations[7]]
set_property PACKAGE_PIN V2 [get_ports operations[6]]					
	set_property IOSTANDARD LVCMOS33 [get_ports operations[6]]
set_property PACKAGE_PIN T3 [get_ports operations[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports operations[5]]
set_property PACKAGE_PIN T2 [get_ports operations[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports operations[4]]
set_property PACKAGE_PIN T1 [ get_ports operations[0]]
set_property IOSTANDARD LVCMOS33 [ get_ports operations[0]]
set_property PACKAGE_PIN U1 [ get_ports operations[1]]
set_property IOSTANDARD LVCMOS33 [ get_ports operations[1]]
set_property PACKAGE_PIN W2 [ get_ports operations[2]]
set_property IOSTANDARD LVCMOS33 [ get_ports operations[2]]
set_property PACKAGE_PIN R3 [ get_ports operations[3]]
set_property IOSTANDARD LVCMOS33 [ get_ports operations[3]]
 # Outputs
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# Define the clock frequency as 100 MHz
#create_clock -period 10.000 [get_ports clk]
#7 segment
set_property PACKAGE_PIN W7 [ get_ports y[6]]
set_property IOSTANDARD LVCMOS33 [ get_ports y[6]]
set_property PACKAGE_PIN W6 [ get_ports y[5]]
set_property IOSTANDARD LVCMOS33 [ get_ports y[5]]
set_property PACKAGE_PIN U8 [ get_ports y[4]]
set_property IOSTANDARD LVCMOS33 [ get_ports y[4]]
set_property PACKAGE_PIN V8 [ get_ports y[3]]
set_property IOSTANDARD LVCMOS33 [ get_ports y[3]]
set_property PACKAGE_PIN U5 [ get_ports y[2]]
set_property IOSTANDARD LVCMOS33 [ get_ports y[2]]
set_property PACKAGE_PIN V5 [ get_ports y[1]]
set_property IOSTANDARD LVCMOS33 [ get_ports y[1]]
set_property PACKAGE_PIN U7 [ get_ports y[0]]
set_property IOSTANDARD LVCMOS33 [ get_ports y[0]]
#
set_property PACKAGE_PIN W4 [ get_ports Anode_Activate[3]]
set_property IOSTANDARD LVCMOS33 [ get_ports Anode_Activate[3]]
set_property PACKAGE_PIN V4 [ get_ports Anode_Activate[2]]
set_property IOSTANDARD LVCMOS33 [ get_ports Anode_Activate[2]]
set_property PACKAGE_PIN U4 [ get_ports Anode_Activate[1]]
set_property IOSTANDARD LVCMOS33 [ get_ports Anode_Activate[1]]
set_property PACKAGE_PIN U2 [ get_ports Anode_Activate[0]]
set_property IOSTANDARD LVCMOS33 [ get_ports Anode_Activate[0]]
